#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

name: CI
on: push

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: shellcheck src/*

    - name: Check GitPack files
      run: shellcheck .gitpack/install/global-Linux/p*
